### ISSUE TITLE
Error: Access denied (403 Forbidden)

### ISSUE THREAD

**Issue by Moon-Launch** [sc4rfurry/ShoDNA#1]
even tho I uploaded correct API in .env file still 403 error

I guess the code is outdated?
 
![image](https://github.com/user-attachments/assets/0e697aac-463d-4a40-9e9f-b9ab5292960d)
![image](https://github.com/user-attachments/assets/cf1148e4-adc7-4cb1-acab-ff745c97bb04)

**Comment by sc4rfurry** [comment]
Hi,
Thanks for opening this issue request, i have validated this and this is not something in my code but the cli library that i,m using to interact with the Shodan's API.
I have ran the above scans and they are working fine. Check the following maybe one of them causing the issue:

- Check your Internet Provider if the API is not restricted in some manner.
- Check your VPN, If you are using a VPN it may cause trouble with the API (Not every VPN - Free ones are to blame)
- Check your .env file make sure that the syntax for the **.env** file is according to the instructions.

I have the screenshots for testing this myself as follow:

![Screenshot 2024-09-17 075735](https://github.com/user-attachments/assets/8caf9e1d-c9d7-4077-8e27-a218caa2fcf2)
